---
- name: restart neutron services
  service: name={{ item }} state=restarted_if_running must_exist=false
  when: restart|default('True')
  failed_when: false
  with_items:
    - "{{ neutron.service_names[os].neutron_server }}"
    - "{{ neutron.service_names[os].neutron_dhcp_agent }}"
    - "{{ neutron.service_names[os].neutron_l3_agent }}"
    - "{{ neutron.service_names[os].neutron_openvswitch_agent }}"
    - "{{ neutron.service_names[os].neutron_linuxbridge_agent }}"
    - "{{ neutron.service_names[os].neutron_metadata_agent }}"
    - "{{ neutron.service_names[os].neutron_lbaasv2_agent }}"
