---
- name: restart glance services
  service: name={{ item }} state=restarted must_exist=false
  when: restart|default('True')
  with_items:
    - "{{ glance.service_names[os].glance_api }}"
    - "{{ glance.service_names[os].glance_registry }}"

# Restarting rsync 3.0.9-1ubuntu1 on 12.04.4 was failing:
#     bind () failed: Address already in use (address-family 2)
# Adding retry logic to workaround
- name: restart rsync
  service: name={{ rsync_service }} state=restarted
  register: result
  until: result|success
  retries: 3
  delay: 10
