---
- block:
  - name: install cinder controller services (ubuntu)
    upstart_service:
      name: "{{ item }}"
      user: cinder
      cmd: /usr/local/bin/{{ item }}
      config_dirs: /etc/cinder
    with_items:
      - "{{ cinder.service_names[os].cinder_api }}"
      - "{{ cinder.service_names[os].cinder_scheduler }}"

  - name: Permit access to Cinder (ubuntu)
    ufw: rule=allow to_port={{ endpoints.cinder.port.haproxy_api }} proto=tcp
    tags: firewall
  when: os == 'ubuntu'

- block:
  - name: install cinder controller services (rhel)
    systemd_service:
      name: "{{ item.0 }}"
      description: OpenStack {{ item.1 }} Service
      type: simple
      user: cinder
      config_files: /etc/cinder/cinder.conf
      cmd: "{{ (ansible_distribution == 'RedHat') | ternary('/usr/bin/', '/usr/local/bin/') }}{{ item.1 }}"
      config_dirs: /etc/cinder
      restart: on-failure
      wanted_by: multi-user.target
    with_together:
      - ["{{ cinder.service_names[os].cinder_api }}",
         "{{ cinder.service_names[os].cinder_scheduler }}"]
      - ["cinder-api","cinder-scheduler"]

  - name: Permit access to Cinder (rhel)
    firewalld:
      state: enabled
      permanent: true
      port: "{{ endpoints.cinder.port.haproxy_api }}/tcp"
    tags: firewall
  when: os == 'rhel'

- name: sync cinder database
  command: cinder-manage db sync
  when: database_create.changed or force_sync|default('false')|bool
  run_once: true
  changed_when: true
  notify: restart cinder services
  # we want this to always be changed so that it can notify the service restart
  tags: db-migrate

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart cinder services
  when: (code_has_changed | default('False') | bool and upgrade | default('False') | bool) or
        (ceph.enabled|default('False')|bool and upgrade_ceph | bool)

- meta: flush_handlers

- name: start cinder controller services
  service: name={{ item }} state=started enabled=true
  with_items:
    - "{{ cinder.service_names[os].cinder_api }}"
    - "{{ cinder.service_names[os].cinder_scheduler }}"

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
