---
# Perform restarts serially as to not take a subservice completely offline.
# Only really matters for nova-api, fix this up later.
- name: restart nova services
  service:
    name: "{{ item[1] }}"
    state: restarted
    must_exist: false
  failed_when: false
  run_once: True
  delegate_to: "{{ item[0] }}"
  when: restart|default('True')
  with_nested:
    - "{{ play_hosts }}"
    - ["{{ nova.service_names[os].nova_api }}",
       "{{ nova.service_names[os].nova_conductor }}",
       "{{ nova.service_names[os].nova_compute }}",
       "{{ nova.service_names[os].nova_consoleauth }}",
       "{{ nova.service_names[os].nova_novncproxy }}",
       "{{ nova.service_names[os].nova_scheduler }}"]
