---
dependencies:
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: ceph
    logdata: "{{ ceph.logs }}"
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.ceph.repo }} {{ ansible_lsb.codename }} main'
        key_url: '{{ apt_repos.ceph.key_url }}'
    when: ('ceph_monitors' in group_names) or ('ceph_osds' in group_names)
