---
stack_env: example_ci-full

state_path_base: /opt/stack/data

neutron:
  enable_external_interface: True
  l3ha:
    enabled: True
    max_agents: 2
    min_agents: 2
    cidr: 169.254.192.0/18
    password: "{{ secrets.service_password }}"
    interval: 2
  lbaas:
    enabled: True

keystone:
  ldap_domain:
    enabled: True
    domain: users

serverspec:
  enabled: True
