---
- name: ifup br-ex
  command: ifup br-ex
  failed_when: False

- name: restart neutron lbaas agent
  service:
    name: "{{ neutron.service_names[os].neutron_lbaasv2_agent }}"
    state: restarted_if_running
  when: restart|default('True') and ((neutron.lbaas.enabled == "smart" and
                     groups['controller'][0] not in groups['compute']) or
                     neutron.lbaas.enabled|bool)

- name: restart xorp
  service: name=xorp state=restarted sleep=10
  ignore_errors: True
