---
  #FIXME Do we need these pkgs on Rhel?
- name: install neutron-data-network packages
  package: name={{ item }}
  with_items:
    - dnsmasq
    - dnsmasq-utils
    - ucarp
    - radvd
  register: result
  until: result|succeeded
  retries: 5

#FIXME can we move this to common systen_tools?
- block:
  - name: install arping (ubuntu)
    package:
      name: iputils-arping

  - name: install resolvconf (ubuntu)
    package:
      name: resolvconf
  when: os == 'ubuntu'

- name: install arping (rhel)
  package:
    name: iputils
  when: os == 'rhel'

#FIXME Do we need this for RHEL?
- name: install packages for l3ha
  package: name=keepalived
  when: neutron.l3ha.enabled|bool
  register: result
  until: result|succeeded
  retries: 5

- name: remove conntrackd
  package: name=conntrackd state=absent
  register: result
  until: result|succeeded
  retries: 5

- include: dnsmasq.yml

- include: igmp-router.yml
  when: os == 'ubuntu' and (
        neutron.plugin == 'ml2' and
        'vxlan' in neutron.tunnel_types
        and not neutron.l2_population )

- name: assert kernel supports vxlan
  command: modinfo -F version vxlan
  changed_when: false
  when: "'vxlan' in neutron.tunnel_types"

- name: assert iproute2 supports vxlan
  command: ip link add type vxlan help
  register: iproute_out
  changed_when: false
  failed_when: iproute_out.rc == 255
  when: "'vxlan' in neutron.tunnel_types"

- block:
  - name: install neutron-data-network services (ubuntu)
    upstart_service:
      name: "{{ item.value.service_name }}"
      user: neutron
      cmd: "/usr/local/bin/{{ item.key }}"
      pidfile: "{{ item.value.pidfile|default(omit) }}"
      start_on: "starting {{ item.value.service_name }}"
      stop_on: "stopping {{ item.value.service_name }}"
      config_dirs: /etc/neutron
      config_files: /etc/neutron/neutron.conf,{{ item.value.config_files }}
      envs: "{{ neutron.service.envs }}"
    with_dict:
      neutron-dhcp-agent:
        service_name: "{{ neutron.service_names[os].neutron_dhcp_agent }}"
        config_files: /etc/neutron/dhcp_agent.ini
      neutron-l3-agent:
        service_name: "{{ neutron.service_names[os].neutron_l3_agent }}"
        config_files: /etc/neutron/l3_agent.ini
        pidfile: /var/run/neutron-l3-agent.pid
      neutron-metadata-agent:
        service_name: "{{ neutron.service_names[os].neutron_metadata_agent }}"
        config_files: /etc/neutron/metadata_agent.ini

  - name: install neutron lbaas service (ubuntu)
    upstart_service:
      name: "{{ item.value.service_name }}"
      user: neutron
      cmd: "/usr/local/bin/{{ item.key }}"
      pidfile: "{{ item.value.pidfile|default(omit) }}"
      start_on: "starting {{ item.value.service_name }}"
      stop_on: "stopping {{ item.value.service_name }}"
      config_dirs: /etc/neutron
      config_files: "{{ item.value.config_files|join(',') }}"
      envs: "{{ neutron.service.envs }}"
    when: ((neutron.lbaas.enabled == "smart" and
           groups['controller'][0] not in groups['compute']) or
           neutron.lbaas.enabled|bool)
    with_dict:
      neutron-lbaasv2-agent:
        service_name: "{{ neutron.service_names[os].neutron_lbaasv2_agent }}"
        config_files:
          - /etc/neutron/neutron.conf
          - /etc/neutron/services/loadbalancer/haproxy/lbaas_agent.ini
          - /etc/neutron/neutron_lbaas.conf
  when: os == 'ubuntu'

- block:
  - name: install neutron-data-network services (rhel)
    systemd_service:
      name: "{{ item.value.service_name }}"
      description: OpenStack {{ item.value.service_name }} Service
      type: simple
      user: neutron
      cmd: "{{ (ansible_distribution == 'RedHat') | ternary('/usr/bin/', '/usr/local/bin/') }}{{ item.key }}"
      config_dirs: /etc/neutron
      config_files: /etc/neutron/neutron.conf,{{ item.value.config_files }}
      #envs: "{{ neutron.service.envs }}"
      restart: on-failure
      kill_mode: process
      wanted_by: multi-user.target
    with_dict:
      neutron-dhcp-agent:
        service_name: "{{ neutron.service_names[os].neutron_dhcp_agent }}"
        config_files: /etc/neutron/dhcp_agent.ini
      neutron-l3-agent:
        service_name: "{{ neutron.service_names[os].neutron_l3_agent }}"
        config_files: /etc/neutron/l3_agent.ini
        #pidfile: /var/run/neutron-l3-agent.pid
      neutron-metadata-agent:
        service_name: "{{ neutron.service_names[os].neutron_metadata_agent }}"
        config_files: /etc/neutron/metadata_agent.ini

  - name: install neutron lbaas service (rhel)
    systemd_service:
      name: "{{ item.value.service_name }}"
      description: OpenStack Neutron "{{ item.value.service_name }}" Service
      type: simple
      user: neutron
      cmd: "{{ (ansible_distribution == 'RedHat') | ternary('/usr/bin/', '/usr/local/bin/') }}{{ item.key }}"
      config_dirs: /etc/neutron
      config_files: "{{ item.value.config_files|join(',') }}"
      #envs: "{{ neutron.service.envs }}"
      restart: on-failure
      kill_mode: process
      wanted_by: multi-user.target
    when: ((neutron.lbaas.enabled == "smart" and
           groups['controller'][0] not in groups['compute']) or
           neutron.lbaas.enabled|bool)
    with_dict:
      neutron-lbaasv2-agent:
        service_name: "{{ neutron.service_names[os].neutron_lbaasv2_agent }}"
        config_files:
          - /etc/neutron/neutron.conf
          - /etc/neutron/services/loadbalancer/haproxy/lbaas_agent.ini
          - /etc/neutron/neutron_lbaas.conf
  when: os == 'rhel'

- name: create lbaas templates folder
  file:
    path: "/etc/neutron/lbaas_templates/"
    state: directory
    owner: root
    group: neutron
    mode: 0755

- name: template neutron lbaas haproxy
  template:
    src: etc/neutron/lbaas_templates/haproxy_base.j2
    dest: /etc/neutron/lbaas_templates/haproxy_base.j2
    owner: root
    group: neutron
    mode: 0644
  notify: restart neutron lbaas agent
  when: (neutron.lbaas.enabled == "smart" and
         groups['controller'][0] not in groups['compute']) or
         neutron.lbaas.enabled|bool

- name: symlink other neutron lbaas haproxy templates
  file:
    src: /opt/openstack/current/neutron/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/drivers/haproxy/templates/{{ item }}
    dest: /etc/neutron/lbaas_templates/{{ item }}
    owner: root
    group: neutron
    state: link
    force: true
  with_items:
    - haproxy.loadbalancer.j2
    - haproxy_proxies.j2
  notify: restart neutron lbaas agent
  when: (neutron.lbaas.enabled == "smart" and
         groups['controller'][0] not in groups['compute']) or
         neutron.lbaas.enabled|bool

- name: neutron lbaas config
  template:
    src: etc/neutron/neutron_lbaas.conf
    dest: /etc/neutron/neutron_lbaas.conf
    owner: root
    group: neutron
    mode: 0644
  when: (neutron.lbaas.enabled == "smart" and
         groups['controller'][0] not in groups['compute']) or
         neutron.lbaas.enabled|bool
  notify:
    - restart neutron lbaas agent

- name: neutron lbaas agent config
  template:
    src: etc/neutron/services/loadbalancer/haproxy/lbaas_agent.ini
    dest: /etc/neutron/services/loadbalancer/haproxy
    mode: 0644
  when: (neutron.lbaas.enabled == "smart" and
         groups['controller'][0] not in groups['compute']) or
         neutron.lbaas.enabled|bool
  notify:
    - restart neutron lbaas agent

- name: kill namespaced neutron processes on upgrade
  command: pkill -f {{ item }}
  failed_when: False
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool
  with_items:
    - neutron-keepalived-state-change
    - neutron-ns-metadata-proxy

- name: trigger restart on upgrades
  debug:
    msg: "Triggering service restart for upgrade"
  changed_when: True
  notify: restart neutron services
  when: code_has_changed | default('False') | bool and
        upgrade | default('False') | bool

- meta: flush_handlers

- name: start neutron-data-network services
  service:
    name: "{{ item }}"
    state: started
    enabled: True
  with_items:
    - "{{ neutron.service_names[os].neutron_l3_agent }}"
    - "{{ neutron.service_names[os].neutron_dhcp_agent }}"
    - "{{ neutron.service_names[os].neutron_metadata_agent }}"

- name: start neutron lbaas agent
  service:
    name: "{{ neutron.service_names[os].neutron_lbaasv2_agent }}"
    state: started
    enabled: True
  when: (neutron.lbaas.enabled == "smart" and
         groups['controller'][0] not in groups['compute']) or
         neutron.lbaas.enabled|bool

- include: ipchanged.yml

- include: monitoring.yml
  tags:
    - monitoring
    - common
  when: monitoring.enabled|default('True')|bool
