---
dependencies:
  - role: endpoints
  - role: apt-repos
    repos:
      - repo: 'deb {{ apt_repos.cloud_archive.repo }} {{ ansible_distribution_release }}-updates/mitaka main'
        key_package: ubuntu-cloud-keyring
  - role: monitoring-common
    when: monitoring.enabled|default(True)|bool
  - role: logging-config
    when: logging.enabled|default(True)|bool
    service: cinder
    logdata: "{{ cinder.logs }}"
  - role: openstack-source
    project_name: cinder
    project_rev: "{{ cinder.source.rev }}"
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    system_dependencies: "{{ cinder.source.system_dependencies }}"
    python_dependencies: "{{ cinder.source.python_dependencies }}"
    constrain: "{{ cinder.source.constrain }}"
    upper_constraints: "{{ cinder.source.upper_constraints }}"
    when: openstack_install_method == 'source'
  - role: openstack-package
    project_name: cinder
    rootwrap: True
    alternatives: "{{ cinder.alternatives }}"
    when: openstack_install_method == 'package'
  - role: ceph-common
    when: ceph.enabled|bool
